# Use postgres/example user/password credentials
version: '3.9'

name: postgres-stack
services:

  db:
    image: postgres
    restart: always
    container_name: postgres
    shm_size: 128mb
    networks:
      - postgres-net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

networks:
  postgres-net:
    name: postgres-net
    driver: bridge

