# Use postgres/example user/password credentials
#version: '3.9'

name: permanent-stack
services:

  db:
    image: postgres
    restart: always
    container_name: postgres
    shm_size: 128mb
    networks:
      - permanent-net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

networks:
  permanent-net:
    name: permanent-net
    driver: bridge

